# Generated by Django 5.0.6 on 2024-06-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
